apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        cni.projectcalico.org/podIP: "10.244.0.28/32"  # Add this line if you have specific annotations for your pods
    spec:
      serviceAccountName: my-service-account
      containers:
      - name: my-container
        image: myregistry/myapp:v1
        ports:
        - containerPort: 80
      tolerations:  # Add the tolerations section here
      - key: "pod"  # Replace "special" with your taint key
        operator: "Equal"
        value: "true"   # Replace "true" with the taint value you want to tolerate
        effect: "NoSchedule"  # Replace "NoSchedule" with the effect of the taint

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-network-policy
spec:
  podSelector:
    matchLabels:
      app: myapp
  policyTypes:
  - Ingress
