apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        cni.projectcalico.org/podIP: "10.244.0.28/32"  # Add this line if you have specific annotations for your pods
    spec:
      serviceAccountName: my-service-account
      networkPolicies:
      - type: Ingress
        podSelector:
          matchLabels:
            app: myapp
      containers:
      - name: charming_diffie
        image: acr0720.azurecr.io/newass:1.0.0
        ports:
        - containerPort: 80
