apiVersion: apps/v1
kind: Deployment
metadata:
  name:docker
  labels:
    app: dockerdep-10-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: docker
  template:
    metadata:
      labels:
        app: docker
    spec:
      containers:
      - name: dockerdep-10-app
        image: dockerdep-10-app:latest
        ports:
        - containerPort: 80
