apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: docker-hpa
  labels:
    app: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: docker
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50 # Adjust this value based on your application's CPU usage requirements
