apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: environment
                operator: In
                values:
                - production
              - key: region
                operator: In
                values:
                - us-west
              - key: type
                operator: In
                values:
                - gpu
      containers:
      - name: my-container
        image: myregistry/myapp:v1
        ports:
        - containerPort: 80
